### ISSUE TITLE
Implement the location claim IPNI advertisement chain (for now, just on our node)

### ISSUE THREAD

**Issue by hannahhoward** [storacha/indexing-service#2]
After storacha/project-tracking#103  is done, start publishing a second advertisement chain to IPNI for location claims. Need to be intentional about where exactly this falls in the W3UP write pipeline and decide who publishes this data (eventually, it will probably be the storage node) so not sure if this happens on `index/add` or later -- spec as part of the ticket.

Out of scope for now: publishing location claims for previous data

**Comment by alanshaw** [comment]
This was completed in the storage node.
