### ISSUE TITLE
Define an HTTP interface for the indexing service based on the Service class, that generally mirrors content claims

### ISSUE THREAD

**Issue by hannahhoward** [storacha/indexing-service#4]
HTTP interface for indexing service should support:
- UCAN invocation to store and publish a content claim / location commitment (these could just be the "assert/*" invocations but I'm not a huge fant)
- UCAN invocation to cache only a location commitment (this could just be "assert/location" and have it not be published)
- get interface to fetch claims ala content claims service

**Comment by alanshaw** [comment]
Initial stubs for HTTP endpoints: https://github.com/storacha/indexing-service/pull/10
