### ISSUE TITLE
The new indexing service returns content claims for data added with blob protocol but published to legacy content claims DB

### ISSUE THREAD

**Issue by hannahhoward** [storacha/indexing-service#7]
# What

When I query for blobs added before the indexing service is released, the indexing service should be able to read legacy content claims for indexes from the database. It should also asynchronously added them to the IPNI advertisement chain.

**Comment by volmedo** [comment]
Core support for this has been implemented by https://github.com/storacha/indexing-service/pull/51 and https://github.com/storacha/indexing-service/pull/52

There are some followup tasks we will work on next:
- [ ] enable access to `content-claims` bucket
- [ ] point to content-claims staging table and bucket for staging deployments
- [ ] store legacy claims in the claims cache

**Comment by volmedo** [comment]
closing this as completed. Remaining work has already been captured in their own issues.
